spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mvc?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: password
  jpa:
    database: mysql
    show-sql: true
